[build]
  command = "bun run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[images]
  remote_images = ["https://images.unsplash.com/*", "https://img.freepik.com/*", "https://static.vecteezy.com/*", "https://c8.alamy.com/*", "https://ext.same-assets.com/*"]
